#!/bin/bash

script_path=$(cd $(dirname "${BASH_SOURCE[0]}") ; pwd)

[ ! -d ${script_path}/../.venv ] && virtualenv ${script_path}/../.venv
. ${script_path}/../.venv/bin/activate

pip install setuptools --upgrade
pip install -r ${script_path}/../test-requirements.txt
